stages:
  - build
  - push
  - deploy

variables:
  DOCKER_IMAGE_NAME: "adumala1/gitopshook"
  DOCKER_IMAGE_TAG: "latest"

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
default:
  tags:
    - docker

deploy_image:
  stage: deploy
  script:
    - echo "Deploying to production."
  only:
    - main  # Adjust this if you want to deploy only from a specific branch

